package com.example.Educational_Platform.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Answer")
public class Answer {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String answerId;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "questionId-index")
    private String questionId;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "respondentId-index")
    private String respondentId;

    @DynamoDBAttribute
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdAt;

    @DynamoDBAttribute
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedAt;
}