package com.example.Educational_Platform.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.Educational_Platform.Utils.DateConverter;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Course")
public class Course {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String courseId;

    @DynamoDBAttribute
    private String courseName;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String branchName;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "instructorId-index")
    private String instructorId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DateConverter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DateConverter.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedAt;
}